name: Project 2 CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
      - 'project2/**'

jobs:
  python-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      
      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.12'
      
      - name: Install ruff
        run: pip install ruff
      
      - name: Format check with ruff
        working-directory: ./project2
        run: ruff format --check .
  
  js-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      
      - name: Set up Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'
      
      - name: Install Biome
        run: npm install -g @biomejs/biome
      
      - name: Format check with Biome (JavaScript)
        working-directory: ./project2
        run: biome format --check "**/*.js"
