name: Project 2 Web Docker Deploy

on:
  push:
    branches: [ main ]
    paths: [ 'project2/**' ]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5.0.0
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          
      - name: Build and push Docker image
        working-directory: ./project2
        run: |
          echo "Building Docker image..."
          docker build -t nutritional-web:latest .
          
          echo "Tagging for GitHub Container Registry..."
          docker tag nutritional-web:latest ghcr.io/${{ github.repository_owner }}/nutritional-web:latest
          
          echo "Pushing to GitHub Container Registry..."
          docker push ghcr.io/${{ github.repository_owner }}/nutritional-web:latest
          
          echo "✅ Docker image built and pushed successfully"
